name: Build the custom Caddy image

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - build/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/caddy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Get caddy tag
        id: tag
        run: echo "tag=$(grep -Eo 'caddy:[0-9]{1,}.[0-9]{1,}.+$' build/Dockerfile | tail -1 | cut -d ':' -f2 | cut -d '-' -f1)" >> $GITHUB_OUTPUT
      - name: Get caddy platform
        id: flavor
        run: echo "flavor=$(grep -Eo 'caddy:[0-9]{1,}.[0-9]{1,}.+$' build/Dockerfile | tail -1 | cut -d ':' -f2 | cut -d '-' -f2)" >> $GITHUB_OUTPUT
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            suffix=-${{ steps.flavor.outputs.flavor }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.tag.outputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.tag.outputs.tag }}
            type=semver,pattern={{major}},value=${{ steps.tag.outputs.tag }}
        
      - name: Build and push container image
        uses: docker/build-push-action@v6
        id: buildpush
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
